apiVersion: v1
kind: Service
metadata:
  name: ethicalzen-gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app: ethicalzen-gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.targetPort }}
