{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ethicalzen-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethicalzen-redis
  template:
    metadata:
      labels:
        app: ethicalzen-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ethicalzen-redis
spec:
  selector:
    app: ethicalzen-redis
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: 6379
{{- end }}
